
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author ismelio-cori
 */
public class CarteiraUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form CarteiraUI
     */
    private static CarteiraUI instancia;

    private String email;

    private CarteiraUI(String email) {
        initComponents();
        this.email = email;

        ActualizarRotulos(email);

    }

    public static CarteiraUI pegarInstancia(String email) {
        if (instancia == null) {
            instancia = new CarteiraUI(email);
        }

        return instancia;
    }

    private void ActualizarRotulos(String email) {
        RepositorioDasCarteiras repositorioDasCarteiras = RepositorioDasCarteiras.pegarInstancia();

        Carteira carteira = repositorioDasCarteiras.consultarCarteira(email);

        this.EmailLabel.setText(carteira.getEmail());
        this.NomeCompletoLabel.setText(carteira.getNomeCompleto());
        this.SaldoLabel.setText(String.valueOf(carteira.getSaldoUnitel()));
        this.SaldoEmMoedaLabel.setText(String.valueOf(carteira.getSaldoEmMoeda()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomeCompletoLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SaldoLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SaldoEmMoedaLabel = new javax.swing.JLabel();
        BotaoSair = new javax.swing.JButton();
        BotaoActualizar = new javax.swing.JButton();
        BotaoConverterSaldoEmMoeda = new javax.swing.JButton();
        BotaoConsultar = new javax.swing.JButton();
        BotaoComprarPlano = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        BotaoLevantarEmMoeda = new javax.swing.JButton();
        ConsultarTransacoes = new javax.swing.JButton();
        BotaoFecharCarteira = new javax.swing.JButton();
        BotaoTransferirSaldoEmMoeda = new javax.swing.JButton();

        jButton3.setText("Consultar actualizações");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel4.setText("Unitel Money");

        jLabel3.setText("Carteira");

        jLabel5.setText("Copyright Ismélio Cori");

        jLabel1.setText("Email:");

        EmailLabel.setText("isme@mail.com");

        jLabel2.setText("Nome Completo:");

        NomeCompletoLabel.setText("isme@mail.com");

        jLabel6.setText("Saldo Unitel:");

        SaldoLabel.setText("0");

        jLabel7.setText("Saldo em Moeda:");

        SaldoEmMoedaLabel.setText("0");

        BotaoSair.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoSair.setText("Sair");
        BotaoSair.setAlignmentX(0.5F);
        BotaoSair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        BotaoActualizar.setText("Actualizar Carteira");
        BotaoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoActualizarActionPerformed(evt);
            }
        });

        BotaoConverterSaldoEmMoeda.setText("Converter Saldo Para Moeda");
        BotaoConverterSaldoEmMoeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConverterSaldoEmMoedaActionPerformed(evt);
            }
        });

        BotaoConsultar.setText("Consultar Carteira");
        BotaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarActionPerformed(evt);
            }
        });

        BotaoComprarPlano.setText("Comprar Plano");
        BotaoComprarPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoComprarPlanoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel8.setText("Obs: Apenas saldo em moeda pode ser levantado");

        BotaoLevantarEmMoeda.setText("Levantar Saldo Em Moeda");
        BotaoLevantarEmMoeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLevantarEmMoedaActionPerformed(evt);
            }
        });

        ConsultarTransacoes.setText("Consultar Transações");
        ConsultarTransacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarTransacoesActionPerformed(evt);
            }
        });

        BotaoFecharCarteira.setText("Fechar Carteira");
        BotaoFecharCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFecharCarteiraActionPerformed(evt);
            }
        });

        BotaoTransferirSaldoEmMoeda.setText("Transferir Saldo Em Moeda");
        BotaoTransferirSaldoEmMoeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTransferirSaldoEmMoedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaldoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaldoEmMoedaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeCompletoLabel))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotaoConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoConverterSaldoEmMoeda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoComprarPlano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoLevantarEmMoeda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConsultarTransacoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoFecharCarteira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoTransferirSaldoEmMoeda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(297, 297, 297))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotaoSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoComprarPlano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(BotaoConverterSaldoEmMoeda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoLevantarEmMoeda))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(EmailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NomeCompletoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(SaldoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(SaldoEmMoedaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoTransferirSaldoEmMoeda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConsultarTransacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoFecharCarteira)
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        // TODO add your handling code here:
        instancia.dispose();
        instancia = null;
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void BotaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarActionPerformed
        // TODO add your handling code here:

        ActualizarRotulos(this.email);

        // create a jframe
        JFrame frame = new JFrame("JOptionPane showMessageDialog");

        // show a joptionpane dialog using showMessageDialog
        JOptionPane.showMessageDialog(frame, "Consulta efetuada com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotaoConsultarActionPerformed

    private void BotaoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoActualizarActionPerformed
        // TODO add your handling code here:

        ActualizarUI telaActualizar = new ActualizarUI(this.email);

        telaActualizar.setLocationRelativeTo(null);

        telaActualizar.setVisible(true);
    }//GEN-LAST:event_BotaoActualizarActionPerformed

    private void BotaoComprarPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoComprarPlanoActionPerformed
        // TODO add your handling code here:

        CompraPlanoUI telaComprar = new CompraPlanoUI(this.email);

        telaComprar.setLocationRelativeTo(null);

        telaComprar.setVisible(true);
    }//GEN-LAST:event_BotaoComprarPlanoActionPerformed

    private void ConsultarTransacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarTransacoesActionPerformed
        // TODO add your handling code here:

        RepositorioDasCarteiras repositorioDasCarteiras = RepositorioDasCarteiras.pegarInstancia();

        String transacoes = repositorioDasCarteiras.consultarTransacoes(email);

        // create a jframe
        JFrame frame = new JFrame("JOptionPane showMessageDialog");

        // show a joptionpane dialog using showMessageDialog
        JOptionPane.showMessageDialog(frame, transacoes, "Transações", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ConsultarTransacoesActionPerformed

    private void BotaoConverterSaldoEmMoedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConverterSaldoEmMoedaActionPerformed
        // TODO add your handling code here:

        Double valor = Double.valueOf(JOptionPane.showInputDialog("Digite o valor a converter:"));

        RepositorioDasCarteiras repositorioDasCarteiras = RepositorioDasCarteiras.pegarInstancia();

        repositorioDasCarteiras.converterEmDinheiro(email, valor);

        ActualizarRotulos(this.email);

    }//GEN-LAST:event_BotaoConverterSaldoEmMoedaActionPerformed

    private void BotaoLevantarEmMoedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLevantarEmMoedaActionPerformed
        // TODO add your handling code here:

        Double valor = Double.valueOf(JOptionPane.showInputDialog("Digite o valor em moeda a levantar:"));

        RepositorioDasCarteiras repositorioDasCarteiras = RepositorioDasCarteiras.pegarInstancia();

        repositorioDasCarteiras.levantarDinheiro(email, valor);

        ActualizarRotulos(this.email);

    }//GEN-LAST:event_BotaoLevantarEmMoedaActionPerformed

    private void BotaoFecharCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFecharCarteiraActionPerformed
        // TODO add your handling code here:

        String password = JOptionPane.showInputDialog("Obs: Após fechar a carteira não será mais possivel logar no sistema \nDigite a password:");

        RepositorioDasCarteiras repositorioDasCarteiras = RepositorioDasCarteiras.pegarInstancia();

        Carteira carteira = repositorioDasCarteiras.consultarCarteira(email);

        if (password.equals(carteira.getPassword())) {
            repositorioDasCarteiras.fecharCarteira(email);
        }

        dispose();

    }//GEN-LAST:event_BotaoFecharCarteiraActionPerformed

    private void BotaoTransferirSaldoEmMoedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTransferirSaldoEmMoedaActionPerformed
        // TODO add your handling code here:
        String emailReceptor = JOptionPane.showInputDialog("Digite o email a receber a tranferência:");

        Double valor = Double.valueOf(JOptionPane.showInputDialog("Digite o valor em moeda a tranferir:"));

        RepositorioDasCarteiras repositorioDasCarteiras = RepositorioDasCarteiras.pegarInstancia();

        repositorioDasCarteiras.realizarTransferencia(email, valor, emailReceptor);

        ActualizarRotulos(email);

    }//GEN-LAST:event_BotaoTransferirSaldoEmMoedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoActualizar;
    private javax.swing.JButton BotaoComprarPlano;
    private javax.swing.JButton BotaoConsultar;
    private javax.swing.JButton BotaoConverterSaldoEmMoeda;
    private javax.swing.JButton BotaoFecharCarteira;
    private javax.swing.JButton BotaoLevantarEmMoeda;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JButton BotaoTransferirSaldoEmMoeda;
    private javax.swing.JButton ConsultarTransacoes;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel NomeCompletoLabel;
    private javax.swing.JLabel SaldoEmMoedaLabel;
    private javax.swing.JLabel SaldoLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
