
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ismelio-cori
 */
public class CompraPlanoUI extends javax.swing.JFrame {

    /**
     * Creates new form CompraPlanoUI
     */
    private int convidados;
    private String email;

    public CompraPlanoUI(String email) {
        initComponents();
        this.convidados = 0;
        this.email = email;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotaoVoltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ComprarPlano500 = new javax.swing.JButton();
        ComprarPlano1000 = new javax.swing.JButton();
        ComprarPlano2000 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        ConvidadosLabel = new javax.swing.JLabel();
        BotaoConvidar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        jScrollPane3.setEnabled(false);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Saldo de\n500Kz ( está na ordem de 100% do saldo, pode ser\nconvertido em moeda ou manter o saldo, se convidar 3\namigos ou mais, terá um bonús de 15%);");
        jScrollPane3.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Compar Plano");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Unitel Money");

        BotaoVoltar.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        BotaoVoltar.setText("←");
        BotaoVoltar.setAlignmentX(0.5F);
        BotaoVoltar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        jLabel6.setText("Copyright Ismélio Cori");

        ComprarPlano500.setText("Comprar Plano 500");
        ComprarPlano500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarPlano500ActionPerformed(evt);
            }
        });

        ComprarPlano1000.setText("Comprar Plano 1000");
        ComprarPlano1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarPlano1000ActionPerformed(evt);
            }
        });

        ComprarPlano2000.setText("Comprar Plano 2000");
        ComprarPlano2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarPlano2000ActionPerformed(evt);
            }
        });

        jScrollPane1.setEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Saldo de 1000Kz(está na ordem de 100% do saldo, que\npode ser convertido em moeda ou manter o saldo, pode ser\nconvertido em moeda ou manter o saldo, se convidar 3\namigos ou mais, terá um bonús de 25%)");
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setEnabled(false);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Saldo de 2000Kz (está na ordem de 100% do saldo, que\npode ser convertido em moeda ou manter o saldo, pode ser\nconvertido em moeda ou manter o saldo, se convidar 3\namigos ou mais, terá um bonús de 50%).");
        jScrollPane2.setViewportView(jTextArea2);

        jScrollPane4.setEnabled(false);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("Saldo de\n500Kz ( está na ordem de 100% do saldo, pode ser\nconvertido em moeda ou manter o saldo, se convidar 3\namigos ou mais, terá um bonús de 15%);");
        jScrollPane4.setViewportView(jTextArea4);

        jLabel2.setText("Convidados:");

        ConvidadosLabel.setText("0");

        BotaoConvidar.setText("Convidar Amigos");
        BotaoConvidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConvidarActionPerformed(evt);
            }
        });

        jScrollPane5.setEnabled(false);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("Obs: Convide antes de comprar \nou não vai receber o bonus.");
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComprarPlano500, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ComprarPlano1000, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComprarPlano2000, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ConvidadosLabel))
                                        .addComponent(BotaoConvidar))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotaoVoltar)
                        .addGap(298, 298, 298)
                        .addComponent(jLabel5)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ComprarPlano500)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ConvidadosLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoConvidar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(ComprarPlano1000)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComprarPlano2000)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void ComprarPlano2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarPlano2000ActionPerformed
        // TODO add your handling code here:
        RepositorioDasCarteiras repositorioDasCarteiras = RepositorioDasCarteiras.pegarInstancia();

        repositorioDasCarteiras.comprarPlano(this.email, Planos.PLANO_2000, convidados);

        dispose();
    }//GEN-LAST:event_ComprarPlano2000ActionPerformed

    private void BotaoConvidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConvidarActionPerformed
        // TODO add your handling code here:
        String numero = JOptionPane.showInputDialog("Digite o telefone do convidado:");

        if (numero.isBlank()) {
            return;
        }

        this.convidados += 1;

        this.ConvidadosLabel.setText(String.valueOf(this.convidados));
    }//GEN-LAST:event_BotaoConvidarActionPerformed

    private void ComprarPlano500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarPlano500ActionPerformed
        // TODO add your handling code here:
        RepositorioDasCarteiras repositorioDasCarteiras = RepositorioDasCarteiras.pegarInstancia();

        repositorioDasCarteiras.comprarPlano(this.email, Planos.PLANO_500, convidados);

        dispose();
    }//GEN-LAST:event_ComprarPlano500ActionPerformed

    private void ComprarPlano1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarPlano1000ActionPerformed
        // TODO add your handling code here:
        RepositorioDasCarteiras repositorioDasCarteiras = RepositorioDasCarteiras.pegarInstancia();

        repositorioDasCarteiras.comprarPlano(this.email, Planos.PLANO_1000, convidados);

        dispose();
    }//GEN-LAST:event_ComprarPlano1000ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConvidar;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JButton ComprarPlano1000;
    private javax.swing.JButton ComprarPlano2000;
    private javax.swing.JButton ComprarPlano500;
    private javax.swing.JLabel ConvidadosLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
}
